### PR TITLE
Able to score existing user

### PR DESCRIPTION
**Pull request by lucky-suman**
The earlier model was not able to score existing user. Now it is doing.

### CODE REVIEW

**Comment by lucky-suman** [comment]
[test]

**Comment by lucky-suman** [comment]
[test]

**Comment by tisnik** [comment]
@lucky-suman please wait till the CI jobs will be fixed.

**Comment by lucky-suman** [comment]
[test]

**Comment by lucky-suman** [comment]
[test]

**Comment by tisnik** [comment]
@lucky-suman please rebase (https://github.com/fabric8-analytics/f8a-hpf-insights/pull/115) to fix build issues

**Comment by lucky-suman** [comment]
[test]

**Comment by lucky-suman** [comment]
[test]

**Pull request merged**
