### PR TITLE
Add feedback logic to scoring

### PR DESCRIPTION
**Pull request by sara-02**
- [x] Add unit tests for USE_FEEDBACK(scoring part only)
- [x] Test the USE_FEEDBACK=false workflow, tests and scoring api
- [x] Test the USE_FEEDBACK=true workflow(scoring part only)  tests and scoring api

### CODE REVIEW

**Comment by sara-02** [comment]
[test]

**Comment by sara-02** [comment]
For this sprint yes, we can talk about it in tomorrow's cabal, and work on a DB based approach next sprint.

**Comment by rootAvish** [comment]
Right, then can you please fix the broken build @sara-02

**Comment by sara-02** [comment]
The test are randomly failing, need to dig a little.

**Comment by sara-02** [comment]
Merging it to test on staging.

**Pull request merged**
